[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "f82744e6beb4cbfe7ad55a9cb9db393b096b2382"
os = "macos"

    [[Triangle.download]]
    sha256 = "73be3bcac246245bb62d9dbf1590ec77503fa70e7650f981e07d403c804e9bfa"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.aarch64-apple-darwin.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "66fcc610ca6dee3a211320b9fc737d3bd3205e09"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "a4b52b148c4ea91529c8fdf29f832d4a737f8aaa0af47428e0d81adbc878c9f5"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.aarch64-linux-gnu.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "910f53879cfb40fda2edb4eb60aa4b3e7ee14b19"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "094f6fb33469d22b698ebd7e1cfd3b28d99dd6445e29f08e906c339879f39f57"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.aarch64-linux-musl.tar.gz"
[[Triangle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8fae5879817773986d2c59c899f8c025d791d56c"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "2b6803a37dd20f9bdc6a41e29754e49073e5297e62f40ac33f0b698e5ddfb0e8"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.armv6l-linux-gnueabihf.tar.gz"
[[Triangle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c0ef87eff6d83e74f1a3dcb908925a87113d2ef7"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "479ce9d41f7d950ec3f11e98ddd746fd4a482156c2dccb7b71042af057f98109"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.armv6l-linux-musleabihf.tar.gz"
[[Triangle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "910425486d68e5ab299bb1c5126032a5bbb584de"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "2309e7de6bf2a5a108f198bd7b1d2376e817fd6e9dee8d9cb760e5c37ab9b0c4"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.armv7l-linux-gnueabihf.tar.gz"
[[Triangle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1e48a9e0500739c0b86fadd67ea0526e61abdfa6"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "572e7aa932e0facdba93e4bf659e36154705ffedb4bf4d54670e074209b78f39"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.armv7l-linux-musleabihf.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "be1cbbf24a6fe7815104a7837f86d2e5c7aa3c91"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "9cea592c7a08d1d1eceb4eaa6b509b2101d12e8272565a045acb6ea901a4f22c"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.i686-linux-gnu.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "549cb4eb753b2eb6480c3d3bb55611ca33a58de8"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "b1582875e0f70456361432664f7288261a2aa3ad5f279f7dfcdb4cc9bf87c8bd"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.i686-linux-musl.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "8bae4c00f905756663785c055d0c78cc8d86a5ca"
os = "windows"

    [[Triangle.download]]
    sha256 = "d3945426ba99b9c3b32e3bf1aea9ece554213425d195b5ca84bb1476a7ef06dc"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.i686-w64-mingw32.tar.gz"
[[Triangle]]
arch = "powerpc64le"
git-tree-sha1 = "43f6aa770f9c0fd9717d2db6bd0d60173a325300"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "d6991457f4d26e7c6257ee702dd9086643fbce5617d8fa955678bfa7f6552dd9"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.powerpc64le-linux-gnu.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "b853ba8584e53d9d0f329ff0195336092b7ee8b5"
os = "macos"

    [[Triangle.download]]
    sha256 = "ba96fbf666eeba6d7a38565666f08ab48d1f50e8e33432aa6e13edc6a02dc78a"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.x86_64-apple-darwin.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "99c572d8828081b45bf6362c1e85990a3bb75ea0"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "c70ffab9e19068a3b839bfd66dadd95af245f5e3401761c1439d07c8b37a4686"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.x86_64-linux-gnu.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "6f89c42aace4260d3b1548a5e60cd5254a46ab59"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "c7f7a7cd844010a26e326cebbb5dce2c59dd408db4c610175480d2974b42e01d"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.x86_64-linux-musl.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "2e453b3acedac7a4fa33fbdf5ac23db09cdcbb3a"
os = "freebsd"

    [[Triangle.download]]
    sha256 = "c688480e3a1b1c485009b2a67711bb83f5a3b2136fe87aae024c9fbc3ff87d94"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.x86_64-unknown-freebsd.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "f8d46bbdf4d69c6b0c39509d9cff4ebfc57b9ba7"
os = "windows"

    [[Triangle.download]]
    sha256 = "ff3712b08a4582cf3796683f1a6556d10a4757b39b1b8049e1b64b244ff38993"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.2+0/Triangle.v1.6.2.x86_64-w64-mingw32.tar.gz"
