[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "1209398b6460b80bec5d37a853d15c9583481427"
os = "macos"

    [[Triangle.download]]
    sha256 = "410a910ec4c609f65a54d0b61b26edc47e7aa73da816e9c701ce8d289849355b"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.aarch64-apple-darwin.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "778bec112945093337555facde204fafddfdd186"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "6c0dbb8b62f157ab46640df904b4c49ee19592ee8ad005fa5a2a60ed191a0230"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.aarch64-linux-gnu.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "adcc5d495bd05ae4a81ff2f9b66a48a50d73ed8b"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "750d2bad21a24483980e0fed9a08acabfc37a048ad7fd88619579bd5bbc93211"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.aarch64-linux-musl.tar.gz"
[[Triangle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "55055effe82a5ed66ef906166061929eb071ee47"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "5779c34d6277f9067d7ce53995fb88c6fda9fb4a80f34a86e60e528e037c9d53"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.armv6l-linux-gnueabihf.tar.gz"
[[Triangle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a84ad4fff40a1bb1a383d666f03e668bc7aa96b5"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "6b6512b492c5641786635190e5af14e91a620b36a82f8403ee0699be066943c0"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.armv6l-linux-musleabihf.tar.gz"
[[Triangle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ca62c14c1c6883ecb73b40832a7dbc493bcd61fc"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "a092a302fe3096422fcda311c4d54d993e6fc9e0c5f4317024d05c0da655b147"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.armv7l-linux-gnueabihf.tar.gz"
[[Triangle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c8ed9ef3c348326c686fb6f502b2838a4880632f"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "d0e3e013bc7cd289771b5f320aec100f227369603dfce1938c3b45972f0574af"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.armv7l-linux-musleabihf.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "4c5acffc95b5d48e1c42a64951d9b103fc5035be"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "9309bab7720a440d7ee9c7153a9fb9b0d00545dab779479ac1e244a27bf54a79"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.i686-linux-gnu.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "ae87b4d5adbf0f1bddb4d9e03c90d0077925d463"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "5ea37b746827eff73cc794b570801294401940c79889e714fbc256fc0c93a1d1"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.i686-linux-musl.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "b8c6fc9531789cf01f35127b3bdee43404d2dc72"
os = "windows"

    [[Triangle.download]]
    sha256 = "3443bbfda6bfb7031ae0e60ce1eeeb8195c44eaf7eb9d15bbe42a81cd2950b07"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.i686-w64-mingw32.tar.gz"
[[Triangle]]
arch = "powerpc64le"
git-tree-sha1 = "0cbc83138a567333a35a3449bc145df20332b143"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "72d97015bb6cd8c4da9a8eaa6407eb02249385ddeee270ace3bda5bce075d769"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.powerpc64le-linux-gnu.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "f3d2f2f43aede5c5e4371cea51beb5fdf5090977"
os = "macos"

    [[Triangle.download]]
    sha256 = "21b4729f84e91c3b78b5f418896d163550746579b85ce199e67673e97d0ade9b"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.x86_64-apple-darwin.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "f8e38190a6b135a9f2890d36b975d0dcb3e1d506"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "d41fb81738e0053daefe09d623b57acf7fe2621f0ec19b5816a06f006b67cd2e"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.x86_64-linux-gnu.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "8017207f390c8b3c9a85eee77d5eb8e9f89f8d51"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "bc83d2690ba4ec74fa1335c077ab4a5af2031c84ad4f1f4591c161594ad616f1"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.x86_64-linux-musl.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "480e200c10cc3a905bea59512824cb68c8cd7da4"
os = "freebsd"

    [[Triangle.download]]
    sha256 = "e91d821d270c29d148374d4ac8a1ba6a586a9b384b957cec8ff2ffd150451fa9"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.x86_64-unknown-freebsd.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "e1ec91c79ccea6375a49b76561b56b09a42c7a47"
os = "windows"

    [[Triangle.download]]
    sha256 = "6bc41181868b0f363d1782fadecd0597b502a0dd75e7c067d6720a764fb8ade8"
    url = "https://github.com/j-fu/Triangle_jll.jl/releases/download/Triangle-v1.6.1+1/Triangle.v1.6.1.x86_64-w64-mingw32.tar.gz"
